# TASK #1: DEFINE SINGLE AND MULTI-DIMENSIONAL  NUMPY ARRAYS

In [1]:
# NumPy is a Linear Algebra Library used for multidimensional arrays
# NumPy brings the best of two worlds: (1) C/Fortran computational efficiency, (2) Python language easy syntax 

import numpy as np

# Let's define a one-dimensional array 
list_1 = [50, 60, 80, 100, 200, 300, 500, 600]
list_1

[50, 60, 80, 100, 200, 300, 500, 600]

In [2]:
# Let's create a numpy array from the list "my_list"
my_array = np.array(list_1)
my_array

array([ 50,  60,  80, 100, 200, 300, 500, 600])

In [3]:
type(my_array)

numpy.ndarray

In [6]:
# Multi-dimensional (Matrix definition) 
my_matrix = np.array([[2, 5, 8], [3, 7, 6]])

MINI CHALLENGE #1: 
- Write a code that creates the following 2x4 numpy array

```
[[3 7 9 3] 
[4 3 2 2]]
```

In [9]:
this_matrix = np.array([[3, 7, 9, 3], [4, 3, 2, 2]])

# TASK #2: LEVERAGE NUMPY BUILT-IN METHODS AND FUNCTIONS 

In [15]:
# "rand()" uniform distribution between 0 and 1
x = np.random.rand(20)

In [16]:
# you can create a matrix of random number as well
x_matrix = np.random.rand(3,3)

In [21]:
# "randint" is used to generate random integers between upper and lower bounds
x = np.random.randint(1, 50)

In [23]:
# "randint" can be used to generate a certain number of random itegers as follows
x = np.random.randint(1, 100, 15)

In [ ]:
# np.arange creates an evenly spaced values within a given interval
x = np.arange(1, 30)

In [25]:
# create a diagonal of ones and zeros everywhere else
x = np.eye(7)

In [30]:
# Matrix of ones
x = np.ones((7, 7))

In [104]:
# Array of zeros
x = np.zeros(8)

MINI CHALLENGE #2:
- Write a code that takes in a positive integer "x" from the user and creates a 1x10 array with random numbers ranging from 0 to "x"

In [44]:
n = int(input("number?"))
np.random.randint(0,n,10)

number? 5


array([2, 0, 2, 1, 4, 4, 2, 0, 0, 0])

# TASK #3: PERFORM MATHEMATICAL OPERATIONS IN NUMPY

In [54]:
# np.arange() returns an evenly spaced values within a given interval
x = np.arange(1,10)

In [55]:
y = np.arange(1,10)

In [59]:
# Add 2 numpy arrays together
sum = x + y

In [61]:
squared = x ** 2

array([ 1,  4,  9, 16, 25, 36, 49, 64, 81])

In [63]:
sqrt = np.sqrt(squared)

In [65]:
z = np.exp(y)

MINI CHALLENGE #3:
- Given the X and Y values below, obtain the distance between them

```
X = [5, 7, 20]
Y = [9, 15, 4]
```

In [77]:
x = np.array([5, 7, 20])
y = np.array([9, 15, 4])
dist = np.sqrt(x**2 + y**2)

# TASK #4: PERFORM ARRAYS SLICING AND INDEXING 

In [94]:
my_array = np.array([3, 5, 6, 2, 8, 10 ,20, 50])

In [81]:
# Access specific index from the numpy array
my_array[4]

8

In [97]:
# Starting from the first index 0 up until and NOT including the last element
my_array[0:-1]

array([ 3,  5,  6,  2,  8, 10, 20])

In [98]:
# Broadcasting, altering several values in a numpy array at once
my_array[0:4] =7

In [109]:
# Let's define a two dimensional numpy array
matrix = np.random.randint(1, 10, (4,4))

In [110]:
# Get a row from a mtrix
matrix_row = matrix[1]

In [111]:
# Get one element
matrix_el = matrix[1, 0]

MINI CHALLENGE #4:
- In the following matrix, replace the last row with 0

```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```



In [132]:
x = np.array([[2, 30, 20, -2, -4], 
               [3, 4,  40, -3, -2],
               [-3, 4, -6, 90, 10],
               [25, 45, 34, 22, 12],
               [13, 24, 22, 32, 37]])
x[4] = np.zeros(5)
x

array([[ 2, 30, 20, -2, -4],
       [ 3,  4, 40, -3, -2],
       [-3,  4, -6, 90, 10],
       [25, 45, 34, 22, 12],
       [ 0,  0,  0,  0,  0]])

# TASK #5: PERFORM ELEMENTS SELECTION (CONDITIONAL)

In [133]:
my_array = np.random.randint(1,10,(5,5))

In [135]:
my_array[my_array>5]

array([9, 7, 6, 6, 6, 6, 9, 9, 9, 8, 9, 9])

In [136]:
# Obtain odd elements only
my_array[my_array%2!=0]

array([9, 7, 5, 3, 5, 5, 9, 1, 9, 5, 1, 1, 3, 9, 9, 9])

MINI CHALLENGE #5:
- In the following matrix, replace negative elements by 0 and replace odd elements with -2


```
X = [2 30 20 -2 -4]
    [3 4  40 -3 -2]
    [-3 4 -6 90 10]
    [25 45 34 22 12]
    [13 24 22 32 37]
```


In [145]:
x = np.array([[2, 30, 20, -2, -4],
    [3, 4,  40, -3, -2],
    [-3, 4, -6, 90, 10],
    [25, 45, 34, 22, 12],
    [13, 24, 22, 32, 37]])
x[x<0] = 0
x[x%2!=0] = -2

In [ ]:
# TASK #6: UNDERSTAND PANDAS FUNDAMENTALS

In [ ]:
# Pandas is a data manipulation and analysis tool that is built on Numpy.
# Pandas uses a data structure known as DataFrame (think of it as Microsoft excel in Python). 
# DataFrames empower programmers to store and manipulate data in a tabular fashion (rows and columns).
# Series Vs. DataFrame? Series is considered a single column of a DataFrame.

In [1]:
import pandas as pd

In [4]:
# Let's define a two-dimensional Pandas DataFrame
# Note that you can create a pandas dataframe from a python dictionary
bank_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444], 'Client Name':['Mike', 'Beth', 'Neal', 'Rob'], 
                           'Net Worth [$]':[100, 150, 500, 300], 'Years w/ bank':[3, 5, 6, 2]})

In [3]:
# Let's obtain the data type 
type(bank_df)

pandas.core.frame.DataFrame

In [7]:
# you can only view the first couple of rows using .head()
bank_df.head(1)

Bank Client ID Client Name  Net Worth [$]  Years w/ bank
0             111        Mike            100              3

In [8]:
# you can only view the last couple of rows using .tail()
bank_df.tail(1)

Bank Client ID Client Name  Net Worth [$]  Years w/ bank
3             444         Rob            300              2

MINI CHALLENGE #6:
- A porfolio contains a collection of securities such as stocks, bonds and ETFs. Define a dataframe named 'portfolio_df' that holds 3 different stock ticker symbols, number of shares, and price per share (feel free to choose any stocks)
- Calculate the total value of the porfolio including all stocks

In [34]:
portfolio_df = pd.DataFrame({'Stock Ticker Symbol':['AAPL', 'GOOG', 'AMZN'], 
                 'Number of Shares':[4, 5, 10], 'Price per Share':[50, 60, 20]})
Totalprices = portfolio_df['Number of Shares'] * portfolio_df['Price per Share']
Totalprices.sum()

700

# TASK #7: PANDAS WITH CSV AND HTML DATA

In [37]:
# Pandas is used to read a csv file and store data in a DataFrame
houseprices_df = pd.read_html('https://www.livingin-canada.com/house-prices-canada.html')

In [ ]:
# Read tabular data using read_html


MINI CHALLENGE #7:
- Write a code that uses Pandas to read tabular US retirement data
- You can use data from here: https://www.ssa.gov/oact/progdata/nra.html 

In [38]:
retirement_data = pd.read_html('https://www.ssa.gov/oact/progdata/nra.html')

# TASK #8: PANDAS OPERATIONS

In [67]:
# Let's define a dataframe as follows:
bank_df = pd.DataFrame({'Bank Client ID':[111, 222, 333, 444], 'Client Name':['Mike', 'Beth', 'Neal', 'Rob'], 
                           'Net Worth [$]':[100, 150, 500, 300], 'Years w/ bank':[3, 5, 6, 2]})

In [68]:
# Pick certain rows that satisfy a certain criteria 
loyal_df = bank_df[bank_df['Years w/ bank'] >= 5]

In [69]:
# Delete a column from a DataFrame
del bank_df['Years w/ bank']

MINI CHALLENGE #8:
- Using "bank_client_df" DataFrame, leverage pandas operations to only select high networth individuals with minimum $5000 
- What is the combined networth for all customers with 5000+ networth?

In [71]:
highnet_df = bank_df[bank_df['Net Worth [$]'] > 150]
highnet_df
highnet_df.sum()['Net Worth [$]']

800

# TASK #9: PANDAS WITH FUNCTIONS

In [75]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})

In [77]:
# Define a function that increases all clients networth (stocks) by a fixed value of 20% (for simplicity sake) 
def increase20(df):
    df = df * 1.2
    return df

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

In [79]:
# You can apply a function to the DataFrame 
bank_client_df['Net worth [$]'].apply(increase20)

0     4200.0
1    34800.0
2    12000.0
3     2400.0
Name: Net worth [$], dtype: float64

MINI CHALLENGE #9:
- Define a function that triples the stock prices and adds $200
- Apply the function to the DataFrame
- Calculate the updated total networth of all clients combined

In [81]:
def triple(x):
    return 3 * x + 200

bank_client_df['Net worth [$]'].apply(triple)
bank_client_df['Net worth [$]'].sum()

44500

# TASK #10: PERFORM SORTING AND ORDERING IN PANDAS

In [84]:
# Let's define a dataframe as follows:
bank_client_df = pd.DataFrame({'Bank client ID':[111, 222, 333, 444], 
                               'Bank Client Name':['Chanel', 'Steve', 'Mitch', 'Ryan'], 
                               'Net worth [$]':[3500, 29000, 10000, 2000], 
                               'Years with bank':[3, 4, 9, 5]})

In [94]:
# You can sort the values in the dataframe according to number of years with bank
bank_client_df.sort_values(by = 'Years with bank', ascending = False)

Bank client ID Bank Client Name  Net worth [$]  Years with bank
2             333            Mitch          10000                9
3             444             Ryan           2000                5
1             222            Steve          29000                4
0             111           Chanel           3500                3

In [98]:
# Note that nothing changed in memory! you have to make sure that inplace is set to True


In [ ]:
# Set inplace = True to ensure that change has taken place in memory 
bank_client_df.sort_values(by = 'Years with bank', inplace = True, ascending = False)

In [ ]:
# Note that now the change (ordering) took place 


# TASK #11: PERFORM CONCATENATING AND MERGING WITH PANDAS

In [ ]:
# Check this out: https://pandas.pydata.org/pandas-docs/stable/user_guide/merging.html

In [103]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
                    'B':['B0','B1','B2','B3'],
                    'C':['C0','C1','C2','C3'],
                    'D':['D0','D1','D2','D3']}, index = [0,1,2,3])

In [104]:
df1

A   B   C   D
0  A1  B1  C1  D1
1  A2  B2  C2  D2
2  A3  B3  C3  D3
3  A4  B4  C4  D4

In [105]:
df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
                    'B':['B4','B5','B6','B7'],
                    'C':['C4','C5','C6','C7'],
                    'D':['D4','D5','D6','D7']}, index = [4,5,6,7])

In [106]:
df2

A   B   C   D
4  A5  B5  C5  D5
5  A6  B6  C6  D6
6  A7  B7  C7  D7
7  A8  B8  C8  D8

In [108]:
df3 = pd.DataFrame({'A':['A8','A9','A10','A11'],
                    'B':['B8','B9','B10','B11'],
                    'C':['C8','C9','C10','C11'],
                    'D':['D8','D9','D10','D11']}, index = [8,9,10,11])

In [110]:
pd.concat([df1,df2,df3])

A    B    C    D
0    A1   B1   C1   D1
1    A2   B2   C2   D2
2    A3   B3   C3   D3
3    A4   B4   C4   D4
4    A5   B5   C5   D5
5    A6   B6   C6   D6
6    A7   B7   C7   D7
7    A8   B8   C8   D8
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

# TASK #12: PROJECT AND CONCLUDING REMARKS

- Define a dataframe named 'Bank_df_1' that contains the first and last names for 5 bank clients with IDs = 1, 2, 3, 4, 5 
- Assume that the bank got 5 new clients, define another dataframe named 'Bank_df_2' that contains a new clients with IDs = 6, 7, 8, 9, 10
- Let's assume we obtained additional information (Annual Salary) about all our bank customers (10 customers) 
- Concatenate both 'bank_df_1' and 'bank_df_2' dataframes
- Merge client names and their newly added salary information using the 'Bank Client ID'
- Let's assume that you became a new client to the bank
- Define a new DataFrame that contains your information such as client ID (choose 11), first name, last name, and annual salary.
- Add this new dataframe to the original dataframe 'bank_df_all'.

In [136]:
bank_df_1 = pd.DataFrame({'Client ID':[1,2,3,4,5],
                          'First Name':['Beth', 'Keith', 'Ben', 'Rob', 'Red'], 
                          'Last Name':['Ruben', 'Tart', 'Ten', 'Zombie', 'Po']}, index = (0,1,2,3,4))
bank_df_2 = pd.DataFrame({'Client ID':[6,7,8,9,10],
                          'First Name':['Mitch','Jen','Dennis','Dan','Mike'],
                          'Last Name':['Feng','Bell','Fast','Lee','Coors']}, index = (5,6,7,8,9))

annualsalary_df = pd.DataFrame({'Client ID':[1,2,3,4,5,6,7,8,9,10], 
                 'Annual Salary':[100000,80000,65000,40000,35000,125000,90000,42500,72500,83500]})

bank_df_3 = pd.concat([bank_df_1, bank_df_2])

bank_df_4 = pd.merge(bank_df_3, annualsalary_df, on='Client ID')

newclient = pd.DataFrame({'Client ID': [11], 'First Name':['Omer'], 'Last Name':['G'], 'Annual Salary':[120000]})

bank_df_all = pd.concat([bank_df_4, newclient], ignore_index=True)
bank_df_all

Client ID First Name Last Name  Annual Salary
0           1       Beth     Ruben         100000
1           2      Keith      Tart          80000
2           3        Ben       Ten          65000
3           4        Rob    Zombie          40000
4           5        Red        Po          35000
5           6      Mitch      Feng         125000
6           7        Jen      Bell          90000
7           8     Dennis      Fast          42500
8           9        Dan       Lee          72500
9          10       Mike     Coors          83500
10         11       Omer         G         120000